# Generated by Django 3.1.2 on 2021-01-21 14:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_disqualified', models.BooleanField(default=False, verbose_name='Czy zdyskwalifkowany')),
                ('guardian_first_name', models.CharField(blank=True, max_length=64, verbose_name='Imię opiekuna')),
                ('guardian_last_name', models.CharField(blank=True, max_length=64, verbose_name='Nazwisko opiekuna')),
                ('school_name', models.CharField(max_length=100, verbose_name='Nazwa szkoły')),
                ('team_as_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Zespół-użytkownik')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='Adres e-mail')),
                ('first_name', models.CharField(max_length=64, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=64, verbose_name='Nazwisko')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(14, 'Wiek musi być pomiędzy 14 a 99'), django.core.validators.MaxValueValidator(99, 'Wiek musi być pomiędzy 14 a 99')], verbose_name='Wiek')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.team', verbose_name='Zespół')),
            ],
        ),
    ]
