# Generated by Django 3.1.2 on 2021-01-23 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(14, 'Wiek musi być pomiędzy 14 a 99'), django.core.validators.MaxValueValidator(99, 'Wiek musi być pomiędzy 14 a 99')], verbose_name='Wiek *'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='Adres e-mail *'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='first_name',
            field=models.CharField(max_length=64, verbose_name='Imię *'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_name',
            field=models.CharField(max_length=64, verbose_name='Nazwisko *'),
        ),
        migrations.AlterField(
            model_name='team',
            name='school_name',
            field=models.CharField(max_length=100, verbose_name='Nazwa szkoły *'),
        ),
    ]
