# Generated by Django 3.1.5 on 2021-01-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210123_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='school_city',
            field=models.CharField(max_length=100, verbose_name='Miasto *'),
            preserve_default=False,
        ),
    ]
