# Generated by Django 3.1.5 on 2021-01-30 10:19
from django.contrib.auth.hashers import make_password
from django.db import migrations


def populate_database(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Group = apps.get_model('auth', 'Group')
    Team = apps.get_model('users', 'Team')
    Participant = apps.get_model('users', 'Participant')
    __create_users(User, Group, Team, Participant)


def __create_users(User, Group, Team, Participant):
    __create_admins(Group, User)
    __create_judges(Group, User)
    __create_teams(Group, User, Team, Participant)


def __create_admins(Group, User):
    admin_group = Group.objects.create(name='admin')

    admin = User.objects.create(username='admin1', email='zbigniew.noga#xample.com', first_name='Zbigniew',
                                last_name='Noga',
                                password=make_password('haslo123'), is_staff=True, is_superuser=True)
    admin.groups.add(admin_group)
    admin.save()


def __create_judges(Group, User):
    judge_group = Group.objects.create(name='judge')
    judge = User.objects.create(username='sedzia1', email='anna.nowak@example.com', first_name='Anna',
                                last_name='Nowak',
                                password=make_password('haslo123'))
    judge.groups.add(judge_group)
    judge.save()


def __create_teams(Group, User, Team, Participant):
    team_group = Group.objects.create(name='team')

    team_1 = __create_team(Team, User, team_group, username='konikowo1', password='haslo123', guardian_first_name='Adam',
                           guardian_last_name='Kowalski',
                           school_name='II Liceum Ogólnokształcące im. Adama Mickiewicza', school_city='Konikowo')

    team_1_participants = [
        __create_participant(Participant, team=team_1, email='grzegorz.lis@example.com', first_name='Grzegorz',
                             last_name='Lis', age=15),
        __create_participant(Participant, team=team_1, email='jolanta.sowa@example.com', first_name='Jolanta',
                             last_name='Sowa', age=16),
        __create_participant(Participant, team=team_1, email='malgorzata.kruk@example.com', first_name='Małgorzata',
                             last_name='Kruk', age=15)
    ]

    team_2 = __create_team(Team, User, team_group, username='sloneczkowo1', password='haslo123',
                           guardian_first_name='Weronika',
                           guardian_last_name='Wino',
                           school_name='IV Liceum Ogólnokształcące im. Mikołaja Kopernika', school_city='Słoneczkowo')

    team_2_participants = [
        Participant.objects.create(email='jerzy.las@example.com', first_name='Jerzy', last_name='Las', age=14,
                                   team=team_2)
    ]

    team_3 = __create_team(Team, User, team_group, username='zygmuntowo1', password='haslo123', guardian_first_name='Michał',
                           guardian_last_name='Rogal',
                           school_name='I Liceum Ogólnokształcące im. Juliusza Słowackiego', school_city='Zygmuntowo')

    team_3_participants = [
        __create_participant(Participant, team=team_3, email='zuzanna.szpak@example.com', first_name='Zuzanna',
                             last_name='Szpak', age=15),
        __create_participant(Participant, team=team_3, email='grazyna.kot@example.com', first_name='Grazyna',
                             last_name='Kot', age=16)

    ]


def __create_team(Team, User, team_group, username, password, guardian_first_name, guardian_last_name, school_name, school_city):
    team_user = User.objects.create(username=username, password=make_password(password))
    team_user.groups.add(team_group)
    team_user.save()
    team = Team.objects.create(team_as_user=team_user, guardian_first_name=guardian_first_name,
                               guardian_last_name=guardian_last_name, school_name=school_name, school_city=school_city)
    return team


def __create_participant(Participant, team, email, first_name, last_name, age):
    return Participant.objects.create(team=team, email=email, first_name=first_name, last_name=last_name, age=age)


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_team_school_city'),
    ]

    operations = [
        migrations.RunPython(populate_database)
    ]
