# Generated by Django 3.1.2 on 2021-01-21 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants_limit', models.PositiveIntegerField()),
                ('competition_status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0)),
                ('ranking_visibility', models.IntegerField(choices=[(0, 'Invisible'), (1, 'Visible')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2048)),
                ('upload_time', models.DateTimeField()),
                ('solution_status', models.IntegerField(choices=[(1, 'Not Evaluated'), (2, 'Correct'), (3, 'Incorrect'), (4, 'Presentation Error'), (5, 'Compilation Error'), (6, 'Runtime Error'), (7, 'Time Exceeded Error')])),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=500)),
                ('output', models.CharField(max_length=500)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.task')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionTestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did_pass', models.BooleanField()),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.solution')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.test')),
            ],
        ),
    ]
