# Generated by Django 3.1.2 on 2021-01-23 21:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210123_2247'),
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='competition.task'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solution',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution_status',
            field=models.IntegerField(choices=[(1, 'Nieocenione'), (2, 'Poprawne'), (3, 'Niepoprawne'), (4, 'Błąd prezentacji'), (5, 'Błąd kompilacji'), (6, 'Błąd czasu wykonania'), (7, 'Przekroczono czas wykonania')], default=1),
        ),
        migrations.AlterField(
            model_name='solution',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
