# Generated by Django 3.1.5 on 2021-01-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('competition', '0003_add_ranking_visibility_time_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='ranking_visibility_change_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='upload_time',
            field=models.DateTimeField(),
        ),
    ]
