# Generated by Django 3.1.5 on 2021-01-29 22:02

from django.db import migrations, models

# Generated by Django 3.1.5 on 2021-01-28 20:58
from django.db import migrations
from django.contrib.auth.hashers import make_password


def __create_team(Team, User, team_group, username, password, guardian_first_name, guardian_last_name, school_name):
    team_user = User.objects.create(username=username, password=make_password(password))
    team_user.groups.add(team_group)
    team_user.save()
    team = Team.objects.create(team_as_user=team_user, guardian_first_name=guardian_first_name,
                               guardian_last_name=guardian_last_name, school_name=school_name)
    return team


def __create_participant(Participant, team, email, first_name, last_name, age):
    return Participant.objects.create(team=team, email=email, first_name=first_name, last_name=last_name, age=age)


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_add_ranking_visibility_time_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='ranking_visibility_change_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='upload_time',
            field=models.DateTimeField(),
        ),
    ]
